# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

RClustalW <- function(rInputSeqs, rCluster, rGapOpen, rGapExtend, rMaxIters, rsubstitutionMatrix, rType, rVerbose, rParams) {
    .Call('_enhancerHomologSearch_RClustalW', PACKAGE = 'enhancerHomologSearch', rInputSeqs, rCluster, rGapOpen, rGapExtend, rMaxIters, rsubstitutionMatrix, rType, rVerbose, rParams)
}

RMuscle <- function(rInputSeq, rCluster, rGapOpening, rGapExtension, rMaxiters, rSubstitutionMatrix, rType, rVerbose, rParams) {
    .Call('_enhancerHomologSearch_RMuscle', PACKAGE = 'enhancerHomologSearch', rInputSeq, rCluster, rGapOpening, rGapExtension, rMaxiters, rSubstitutionMatrix, rType, rVerbose, rParams)
}

